In [1]:
import pandas as pd
import joblib
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
# load unnormalised dataset
FEATURE_COLUMNS = ['d_front', 'd_back', 'v_front', 'v_back']
dataset = pd.read_csv('simulation-dataset.csv')
training_datas_unnormalised = dataset[FEATURE_COLUMNS].values



unnormalised_mins = training_datas_unnormalised.min(axis=0)
unnormalised_maxs = training_datas_unnormalised.max(axis=0)

details = pd.DataFrame({
    'Features': FEATURE_COLUMNS,
    'Data Min': unnormalised_mins,
    'Data Max': unnormalised_maxs
})
print(details.to_string())

# load scaler file and normalise
scaler = joblib.load('scaler.pkl')
training_datas = scaler.transform(training_datas_unnormalised)
print(f"\nFirst 5 lines of dataset")
print(f"{training_datas[:5]}\n")

LABEL_COLUMN = 'ego_a'
training_labels= dataset[LABEL_COLUMN].values
print(f"\nFirst 5 lines of labels")
print(f"{training_labels[:5]}\n")

# find normalise rule
print(f"Scaler type: {scaler}")
details = pd.DataFrame({
        'features': FEATURE_COLUMNS,
        'Mean': scaler.mean_,
        'SD': scaler.scale_
    })
print(details.to_string())
print("\nNormalisation law:\nX = (X_unnorm - Mean) / SD )")

"""
vehicle verify \
  --specification car-robust-safety.vcl \
  --network nnModel:nn_model.onnx \
  --parameter epsilon:0.005 \
  --dataset trainingInputs:trainingDatas.idx \
  --dataset trainingLabels:trainingLabels.idx \
  --verifier Marabou
"""


"""
vehicle verify \
  --specification car-safety.vcl \
  --verifier Marabou \
  --network nnModel:nn_model.onnx \
  --property property1
"""

  Features  Data Min    Data Max
0  d_front -0.092464  311.600923
1   d_back -0.077204  305.828968
2  v_front -5.563068    7.548104
3   v_back -5.361264    7.422031

First 5 lines of dataset
[[-0.44419482 -0.89480449 -0.18360143 -0.36255772]
 [-0.44453579 -0.89436008 -0.34954271 -0.12819463]
 [-0.44521975 -0.89295106 -0.35052217  0.14612772]
 [-0.44591738 -0.89053062 -0.3561972   0.40518206]
 [-0.44664011 -0.88761082 -0.362737    0.40946246]]


First 5 lines of labels
[0. 3. 3. 3. 3.]

Scaler type: StandardScaler()
  features       Mean         SD
0  d_front  68.479297  52.128595
1   d_back  69.437695  52.274740
2  v_front   0.393321   2.142253
3   v_back   0.718784   1.982537

Normalisation law:
X = (X_unnorm - Mean) / SD )


'\nvehicle verify   --specification car-safety.vcl   --verifier Marabou   --network nnModel:nn_model.onnx   --property property1\n'

Constance - lab3
introduce, say we each tried the basic acasxu exercises
TODO: add safety properties
explain approximation due to marabou limitation
Show an example

In [ ]:
Ocean - robustness